# Generated by Django 4.0.6 on 2022-08-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_teacher_remove_pair_subject_alter_group_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='cabinet',
        ),
        migrations.AddField(
            model_name='lessons',
            name='cabinet',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
