# Generated by Django 4.0.6 on 2022-08-04 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_time_rename_day_dayoftheweek'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.AlterModelOptions(
            name='dayoftheweek',
            options={'verbose_name': 'День', 'verbose_name_plural': 'Дни'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='pair',
            options={'verbose_name': 'Пара', 'verbose_name_plural': 'Пары'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'Время', 'verbose_name_plural': 'Времена'},
        ),
        migrations.RemoveField(
            model_name='pair',
            name='day',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='group',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='lessons',
        ),
        migrations.AddField(
            model_name='pair',
            name='cabinet',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pair',
            name='subject',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app.subject', verbose_name='Предмет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pair',
            name='teacher',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app.teacher', verbose_name='Имя учителя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='time',
            name='time',
            field=models.CharField(max_length=16, verbose_name='Время начало пары'),
        ),
        migrations.DeleteModel(
            name='Lessons',
        ),
        migrations.AddField(
            model_name='timetable',
            name='day',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.dayoftheweek'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.group'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='pair',
            field=models.ManyToManyField(to='app.pair'),
        ),
    ]
