# Generated by Django 4.0.6 on 2022-08-04 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_timetable_alter_dayoftheweek_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.teacher', verbose_name='Имя учителя'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.dayoftheweek'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.group'),
        ),
    ]
