# Generated by Django 4.0.6 on 2022-08-04 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0001_initial'),
        ('app', '0009_alter_pair_teacher_delete_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='day.dayoftheweek'),
        ),
        migrations.DeleteModel(
            name='DayOfTheWeek',
        ),
    ]
