# Generated by Django 4.0.6 on 2022-08-04 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_alter_myuser_group'),
        ('group', '0001_initial'),
        ('app', '0010_alter_timetable_day_delete_dayoftheweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
