# Generated by Django 4.0.6 on 2022-08-04 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('app', '0011_alter_timetable_group_delete_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subject.subject', verbose_name='Предмет'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
